### ISSUE TITLE
xy axis orientation problem

### ISSUE THREAD

**Issue by laldoroty** [Roman-Supernova-PIT/diff-img#11]
There is some confusion over the x-y axis orientation. Previously, there was an issue causing the difference images to be mirrored and misaligned (https://github.com/laldoroty/phrosty/issues/8), but this clearly still persists in the mk_lc.py function. The bad news is I'm not sure why the difference images are now aligned and fine. 

In DS9, I'm seeing 3 "options" for axis orientation. 
4k cutout of my coadd (and everything else I've aligned with SWarp, including the image I'm getting the stars for the zeropoint from):
![image](https://github.com/user-attachments/assets/f8b201c0-62a0-4783-ae7f-2c0bacb1b669)

Original image, SCA ID%3 != 0: 
![image](https://github.com/user-attachments/assets/4b7eab8a-85b8-4be7-8170-21375521e2f8)

Original image, SCA ID%3 = 0:
![image](https://github.com/user-attachments/assets/17fe5575-4198-4d16-b5bd-6faa7a27e3ab)

Showing up as this error:
```
Traceback (most recent call last):
  File "/hpc/group/cosmology/lna18/rsim_photometry/mk_lc.py", line 233, in <module>
    main(sys.argv)
  File "/hpc/group/cosmology/lna18/rsim_photometry/mk_lc.py", line 230, in main
    lc(o_id,band)
  File "/hpc/group/cosmology/lna18/rsim_photometry/mk_lc.py", line 172, in lc
    xm = crossmatch(res, stars)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/phrosty/phrosty/photometry.py", line 219, in crossmatch
    ti_x_pi = join(ti,ti_pi_reduced,join_type='outer')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/table/operations.py", line 415, in join
    out = _join(
          ^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/table/operations.py", line 1222, in _join
    raise ValueError("input tables for join must both have at least one row")
ValueError: input tables for join must both have at least one row
```

...because it thinks that there are no stars that both tables share. 

@wmwv, can you post that plot you made showing that the stars don't overlap, but appear to be mirror imaged?

**Comment by laldoroty** [comment]
Fixed it. We need to always make sure we're aligning to the 4k cutout of the coadd. 

![image](https://github.com/user-attachments/assets/0c152401-049d-4cc5-a457-741cc25c85ed)
