### ISSUE TITLE
Coadds not saving

### ISSUE THREAD

**Issue by laldoroty** [Roman-Supernova-PIT/diff-img#13]
I guess when I was testing on R band, I created the file in a Jupyter notebook, but now that I'm trying to run on other bands...

```
Traceback (most recent call last):
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 292, in <module>
    main(sys.argv)
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 289, in main
    sfft_and_animate(o_id,band)
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 129, in sfft_and_animate
    coadd_img_path, coadd_img_paths_all = swarp_coadd_img(skysub_ref,skysub_ref_init[0],f'{oid}_{band}_{refvisit}_{refsca}_coadd.fits')
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/phrosty/phrosty/imagesubtraction.py", line 539, in swarp_coadd_img
    coadd = PY_SWarp.Coadd(FITS_obj=imgpaths, FITS_ref=refpath, ConfigDict=cd,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/sfft/sfft/utils/pyAstroMatic/PYSWarp.py", line 318, in Coadd
    PixA_resamp = fits.getdata(OUT_path, ext=0).T
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/convenience.py", line 220, in getdata
    hdulist, extidx = _getext(filename, mode, *args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/convenience.py", line 1121, in _getext
    hdulist = fitsopen(filename, mode=mode, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 222, in fitsopen
    return HDUList.fromfile(
           ^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 486, in fromfile
    return cls._readfrom(
           ^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 1169, in _readfrom
    fileobj = _File(
              ^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/file.py", line 218, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/file.py", line 641, in _open_filename
    self._file = open(self.name, IO_FITS_MODES[mode])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/work/lna18/imsub_out/coadd/20172782_Y106_116_17_coadd.fits'
```

**Comment by laldoroty** [comment]
When I run `sfft_and_animate.py` as a batch script, the swarp command in PYSWarp.Coadd() fails. However, when I just run it in the command line directly, it is fine:
`cd /work/lna18/tmpdir && swarp /work/lna18/imsub_out/skysub/skysub_Roman_TDS_simple_model_Y106_116_17.fits /work/lna18/imsub_out/skysub/skysub_Roman_TDS_simple_model_Y106_2038_10.fits /work/lna18/imsub_out/skysub/skysub_Roman_TDS_simple_model_Y106_2424_6.fits /work/lna18/imsub_out/skysub/skysub_Roman_TDS_simple_model_Y106_2429_8.fits /work/lna18/imsub_out/skysub/skysub_Roman_TDS_simple_model_Y106_2819_7.fits -IMAGEOUT_NAME /work/lna18/imsub_out/coadd/20172782_Y106_116_17_coadd.fits -WEIGHTOUT_NAME /work/lna18/imsub_out/coadd/20172782_Y106_116_17_coadd.weight.fits -c /work/lna18/tmpdir/PYSWarp.swarp`

**Comment by laldoroty** [comment]
If I make the temporary directory and copy and paste the above command into the terminal, it works.

**Comment by laldoroty** [comment]
I added print statements around the code in swarp_coadd_psf() to check where it's failing: 
```
    print('COADD_PSF_SAVEPATH')
    print(coadd_psf_savepath)
    psf_list = []
    # Can be parallelized: 
    for i, row in enumerate(ref_table):
        psf = rotate_psf(ra,dec,sci_skysub_paths[i],sci_imalign_paths[i],
                         sci_band=row['filter'],sci_pointing=row['pointing'],sci_sca=row['sca'],
                         ref_path=refpath)
        psf_list.append(psf)

    coadd_psf_init, imgpaths = swarp_coadd_img(imgpath_list=psf_list,
                                               refpath=refpath,
                                               out_name=coadd_psf_savepath)

    print('COADD_PSF_SAVEPATH AGAIN')
    print(coadd_psf_savepath)
    return coadd_psf_savepath
```
'COADD_PSF_SAVEPATH AGAIN' never prints. Adding a print statement inside swarp_coadd_img() right before the return line.

**Comment by laldoroty** [comment]
The print statement inside swarp_coadd_img() prints for the coadded image, but not for the coadded PSF.

**Comment by laldoroty** [comment]
I think there is conflicting directory information between the two functions. Check this next time I look at it.

**Comment by laldoroty** [comment]
Yeah--so what I think is happening is swarp_coadd_psf() makes a folder and filename for the files:
```
    coadd_psf_savedir = os.path.join(out_path,'coadd_psf')
    check_and_mkdir(coadd_psf_savedir)
    coadd_psf_savepath = os.path.join(coadd_psf_savedir,out_name)
```

But then I call swarp_coadd_img(), which _also_ makes a folder and filename for the files, and uses this to create and save the image. So, when I input the savepath from swarp_coadd_psf() into swarp_coadd_img(), it doesn't know what to do with it because the path that swarp_coadd_img() creates is hardcoded into itself. 

I should just combine these functions to avoid this nonsense completely, and set up the PSF retrieval/rotation outside of these in sfft_and_animate.py instead.

**Comment by laldoroty** [comment]
Did the above. I think I'm on the right track. It's no longer hitting the line where SWarp prints "all done" before failing. 
```
MeLOn CheckPoint: Run SWarp Command ... 
 cd /tmp/PYSWarp_mh_0389j && swarp /work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_116_17.fits /work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_116_17.fits /work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_116_17.fits /work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_116_17.fits /work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_116_17.fits -IMAGEOUT_NAME /work/lna18/imsub_out/coadd_psf/20172782_Y106_35193_8_coadd_psf.fits -WEIGHTOUT_NAME /work/lna18/imsub_out/coadd_psf/20172782_Y106_35193_8_coadd_psf.weight.fits -c /tmp/PYSWarp_mh_0389j/PYSWarp_udtx0r2nswarp_config/PYSWarp.swarp
----- SWarp 2.38.0 started on 2024-07-18 at 14:19:05 with 78 threads

> Examining input data ...
> *Error*: /work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_116_17.weight.fits not found

Traceback (most recent call last):
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 309, in <module>
    main(sys.argv)
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 306, in main
    sfft_and_animate(o_id,band)
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 181, in sfft_and_animate
    coadd_psf_path, psfpaths = swarp_coadd_img(imgpath_list=template_psf_list,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/phrosty/phrosty/imagesubtraction.py", line 547, in swarp_coadd_img
    coadd = PY_SWarp.Coadd(FITS_obj=imgpaths, FITS_ref=refpath, ConfigDict=cd,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/sfft/sfft/utils/pyAstroMatic/PYSWarp.py", line 320, in Coadd
    PixA_resamp = fits.getdata(OUT_path, ext=0).T
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/convenience.py", line 220, in getdata
    hdulist, extidx = _getext(filename, mode, *args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/convenience.py", line 1121, in _getext
    hdulist = fitsopen(filename, mode=mode, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 222, in fitsopen
    return HDUList.fromfile(
           ^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 486, in fromfile
    return cls._readfrom(
           ^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 1169, in _readfrom
    fileobj = _File(
              ^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/file.py", line 218, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/file.py", line 641, in _open_filename
    self._file = open(self.name, IO_FITS_MODES[mode])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/work/lna18/imsub_out/coadd_psf/20172782_Y106_35193_8_coadd_psf.fits'
```

**Comment by laldoroty** [comment]
Printed the inputs to PY_SWarp.Coadd(). They all seem fine to me.
```
FITS_obj
['/work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_116_17.fits', '/work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_2038_10.fits', '/work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_2424_6.fits', '/work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_2429_8.fits', '/work/lna18/imsub_out/psf/rot_psf_7.551093401915147_-44.80718106491529_Y106_2819_7.fits']
FITS_ref
/work/lna18/imsub_out/coadd/cutouts_4k/20172782_Y106_35193_8_coadd_4kcutout.fits
OUT_path
/work/lna18/imsub_out/coadd_psf/20172782_Y106_35193_8_coadd_psf.fits
```

**Comment by laldoroty** [comment]
A thought. I recall having some issue with swarp-combining images I've already aligned using SWarp. I think I should not rotate the PSFs and let SWarp handle that only once. This means updating the fits headers of the PSFs to contain the correct WCS information. 
```
>>> from astropy.io import fits
>>> from astropy.wcs import WCS
>>> hdu = fits.open('rot_psf_7.551093401915147_-44.80718106491529_Z087_9725_10.fits')
>>> wcs = WCS(hdu[0].header)
>>> wcs
WCS Keywords

Number of WCS axes: 2
CTYPE : '' '' 
CRVAL : 0.0 0.0 
CRPIX : 0.0 0.0 
PC1_1 PC1_2  : 1.0 0.0 
PC2_1 PC2_2  : 0.0 1.0 
CDELT : 1.0 1.0 
NAXIS : 501  501
>>> hdu[0].header
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -32 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                  501                                                  
NAXIS2  =                  501                                                  
EXTEND  =                    T 
```

**Comment by laldoroty** [comment]
After grilling Troxel about it, there is a better way to get the PSFs from roman_imsim. I have been using:
```
psf = config.getPSF_Image(501, x=pxradec[0], y=pxradec[1]).array.T 

return psf
```

However, I can use config.getPSF_Image().write('filepath.fits'). This has a header that looks like:
```
>>> hdu[0].header
SIMPLE  =                    T / conforms to FITS standard                      
BITPIX  =                  -32 / array data type                                
NAXIS   =                    2 / number of array dimensions                     
NAXIS1  =                   50                                                  
NAXIS2  =                   50                                                  
EXTEND  =                    T                                                  
GS_XMIN =                    1 / GalSim image minimum x coordinate              
GS_YMIN =                    1 / GalSim image minimum y coordinate              
GS_WCS  = 'JacobianWCS'        / GalSim WCS name                                
CTYPE1  = 'LINEAR  '           / name of the world coordinate axis              
CTYPE2  = 'LINEAR  '           / name of the world coordinate axis              
CRVAL1  =                  0.0 / world coordinate at reference pixel = u0       
CRVAL2  =                  0.0 / world coordinate at reference pixel = v0       
CRPIX1  =                  0.0 / image coordinate of reference pixel = x0       
CRPIX2  =                  0.0 / image coordinate of reference pixel = y0       
CD1_1   = 0.044032855627615275 / CD1_1 = dudx                                   
CD1_2   =  0.09909067452649178 / CD1_2 = dudy                                   
CD2_1   =   0.1007490882245945 / CD2_1 = dvdx                                   
CD2_2   = -0.04266790270019648 / CD2_2 = dvdy   
```
Then, because this defines the Jacobian at the corner of the image, I need to do an affine transform to center it at the center of the PSF image (https://galsim-developers.github.io/GalSim/_build/html/wcs.html#galsim.AffineTransform). I can use wcs.affine(image_pos=new_pos) to change it. 

I would also need to make sure to transpose hdu[0].data so it's consistent for the SFFT pipeline.

**Comment by laldoroty** [comment]
Okay, here's my little how-to. 
```
from phrosty.utils import get_transient_radec, get_fitsobj
from phrosty.plotting import showimage
from galsim import PositionD # Floating point position class
from astropy.io import fits
from astropy.wcs import WCS
from astropy.coordinates import SkyCoord
from astropy.visualization import ZScaleInterval
import astropy.units as u
from roman_imsim.utils import roman_utils
import matplotlib.pyplot as plt
import numpy as np

aux = '/hpc/group/cosmology/lna18/phrosty/phrosty/auxiliary/tds.yaml'
oid = 20172782
band, pointing, sca = 'R062',6,17
ra,dec = get_transient_radec(oid)
coord = SkyCoord(ra=ra*u.deg,dec=dec*u.deg)
hdu = get_fitsobj(band=band,pointing=pointing,sca=sca)
wcs = WCS(hdu[0].header)
x,y = wcs.world_to_pixel(coord)
writepath = f'/work/lna18/imsub_out/psf/psf_{ra}_{dec}_{band}_{pointing}_{sca}.fits'

config = roman_utils(aux,pointing,sca)
psf = config.getPSF_Image(501,x,y)
pos = PositionD(x=x,y=y)
wcs_new = psf.wcs.affine(image_pos=pos)
psf.wcs = wcs_new
psf.write(writepath)

hdu = fits.open(writepath) # Need to reopen this and transpose the data there because I ran into 'property "array" of "Image" object has no setter' when I tried doing psf.array = psf.array.T
hdu[0].data = hdu[0].data.T
hdu.writeto(writepath,overwrite=True)
```

**Comment by wmwv** [comment]
I don't really understand the transpose thing.  Why does SFFT need the transpose?

**Comment by laldoroty** [comment]
Because the entire SFFT package uses the convention that the data array is transposed.

**Comment by wmwv** [comment]
I think I don't understand.  Isn't it arbitrary whether one is row-major or column-major?  You just have to be consistent?

**Comment by laldoroty** [comment]
Yes--every time an image is read or saved in SFFT, the code takes the transpose of the array. So I need to save things that go into SFFT as a transposed array. It opens transposed matrices, does stuff to them, and then re-transposes and saves. 
https://github.com/thomasvrussell/sfft/blob/master/sfft/CustomizedPacket.py#L89

**Comment by laldoroty** [comment]
The good news is that gutting the way the PSFs are retrieved, saved, and rotated didn't break the code, and I'm still hitting the same error when I try to coadd the PSFs. The bad news is I'm still getting the same error when I try to coadd the PSFs. It still works for the full coadded mosaic. 

```
MeLOn CheckPoint: Run SWarp Command ... 
 cd /tmp/PYSWarp_13ge_3uk && swarp /work/lna18/imsub_out/psf/psf_7.551093401915147_-44.80718106491529_Y106_116_17.fits /work/lna18/imsub_out/psf/psf_7.551093401915147_-44.80718106491529_Y106_2038_10.fits /work/lna18/imsub_out/psf/psf_7.551093401915147_-44.80718106491529_Y106_2424_6.fits /work/lna18/imsub_out/psf/psf_7.551093401915147_-44.80718106491529_Y106_2429_8.fits /work/lna18/imsub_out/psf/psf_7.551093401915147_-44.80718106491529_Y106_2819_7.fits -IMAGEOUT_NAME /work/lna18/imsub_out/coadd_psf/20172782_Y106_35193_8_coadd_psf.fits -WEIGHTOUT_NAME /work/lna18/imsub_out/coadd_psf/20172782_Y106_35193_8_coadd_psf.weight.fits -c /tmp/PYSWarp_13ge_3uk/PYSWarp_5djnn6jpswarp_config/PYSWarp.swarp
----- SWarp 2.38.0 started on 2024-07-18 at 17:36:10 with 78 threads

> Examining input data ...
> *Error*: /work/lna18/imsub_out/psf/psf_7.551093401915147_-44.80718106491529_Y106_116_17.weight.fits not found

Traceback (most recent call last):
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 306, in <module>
    main(sys.argv)
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 303, in main
    sfft_and_animate(o_id,band)
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 181, in sfft_and_animate
    coadd_psf_path, psfpaths = swarp_coadd_img(imgpath_list=template_psf_list,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/phrosty/phrosty/imagesubtraction.py", line 587, in swarp_coadd_img
    coadd = PY_SWarp.Coadd(FITS_obj=imgpaths, FITS_ref=refpath, ConfigDict=cd,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/sfft/sfft/utils/pyAstroMatic/PYSWarp.py", line 320, in Coadd
    PixA_resamp = fits.getdata(OUT_path, ext=0).T
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/convenience.py", line 220, in getdata
    hdulist, extidx = _getext(filename, mode, *args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/convenience.py", line 1121, in _getext
    hdulist = fitsopen(filename, mode=mode, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 222, in fitsopen
    return HDUList.fromfile(
           ^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 486, in fromfile
    return cls._readfrom(
           ^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/hdu/hdulist.py", line 1169, in _readfrom
    fileobj = _File(
              ^^^^^^
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/file.py", line 218, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/hpc/group/cosmology/lna18/miniconda3/envs/repeatability/lib/python3.11/site-packages/astropy/io/fits/file.py", line 641, in _open_filename
    self._file = open(self.name, IO_FITS_MODES[mode])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/work/lna18/imsub_out/coadd_psf/20172782_Y106_35193_8_coadd_psf.fits'
```

**Comment by laldoroty** [comment]
mmmmmm the other bad news is the output looks crazy 
![image](https://github.com/user-attachments/assets/8c8f356f-6051-4da9-8e66-57a1b072abda)

**Comment by laldoroty** [comment]
Okay. I'm fried for the day. Summary:
- I am not able to make it fail in the terminal, so it must be somewhere in my Python wrapper for SWarp.
- It works for the coadd template image, but not the PSF coadd, so it must have something to do with the PSFs.
- I eliminated two entire functions (swarp_coadd_psf and rotate_psf) from the PSF coaddition step

**Comment by wmwv** [comment]
Does Swarp know how to coadd PSFs?  I'm sensing the answer is no, it doesn't know anything special about them so instead you have to feed it a thing that is an image exactly aligned.  You don't really want a full WCS, but rather just the rotation matrix.

When I look at the WCS for the PSF files, I see things like:
```
GS_WCS  = 'AffineTransform'    / GalSim WCS name                                
CTYPE1  = 'LINEAR  '           / name of the world coordinate axis              
CTYPE2  = 'LINEAR  '           / name of the world coordinate axis              
CRVAL1  =  -347.00793890391725 / world coordinate at reference pixel = u0       
CRVAL2  =    243.3111579925501 / world coordinate at reference pixel = v0       
CRPIX1  =     3167.59201485829 / image coordinate of reference pixel = x0       
CRPIX2  =   2247.2583100556526 / image coordinate of reference pixel = y0       
CD1_1   = -0.10799018359621737 / CD1_1 = dudx                                   
CD1_2   = -0.00219783174873922 / CD1_2 = dudy                                   
CD2_1   = 0.001247801388696990 / CD2_1 = dvdx                                   
CD2_2   =  0.10651140156275885 / CD2_2 = dvdy
```

and
```
GS_WCS  = 'AffineTransform'    / GalSim WCS name                                
CTYPE1  = 'LINEAR  '           / name of the world coordinate axis              
CTYPE2  = 'LINEAR  '           / name of the world coordinate axis              
CRVAL1  =  -189.75909248410068 / world coordinate at reference pixel = u0       
CRVAL2  =   -275.8411189309953 / world coordinate at reference pixel = v0       
CRPIX1  =   3100.0282045535396 / image coordinate of reference pixel = x0       
CRPIX2  =    240.1685487576857 / image coordinate of reference pixel = y0       
CD1_1   = -0.05421338482127558 / CD1_1 = dudx                                   
CD1_2   = -0.09033685129072228 / CD1_2 = dudy                                   
CD2_1   = -0.09335584816625218 / CD2_1 = dvdx                                   
CD2_2   =  0.05647968276683095 / CD2_2 = dvdy
```

But I think you want CRPIX1, CRPIX2, CRVAL1, CRVAL2 to have the same values for each PSF image, such that CRPIX1, CRPIX2 point to the middle of the array of the PSF.  And then the CD matrix contains the rotation about this point.

**Comment by wmwv** [comment]
I noticed that each of the example above of coadding the PSF had the line
```
> *Error*: /work/lna18/imsub_out/psf/psf_7.551093401915147_-44.80718106491529_Y106_116_17.weight.fits not found
```

And "Error" seems seems important.  What's your explanation for this error, and how can you make it go away?

**Comment by wmwv** [comment]
When you add a whole bunch of rotated PSFs, which are in principle essentially circular in power, but you are combining realizations on square grids, which thus either contain extra at the corners, or truncate at the sides (depending on how you want to think about it), what do you do about the resulting coaddition of a bunch of different orientations?

It seems like you would need to do PSF stamps sqrt(2) larger than you will eventually use, and then trim back down.

**Comment by wmwv** [comment]
Glad you found the issue.  I'm happy to review the PR quickly for the fix so we can close this issue.
