### ISSUE TITLE
Masked source error?

### ISSUE THREAD

**Issue by laldoroty** [Roman-Supernova-PIT/diff-img#20]
@wmwv , when you were refactoring mk_lc.py, were you getting an error like this? I have all my difference images, so now I'm trying to run them through mk_lc.py. 

```
Traceback (most recent call last):
  File "/hpc/group/cosmology/lna18/rsim_photometry/mk_lc.py", line 558, in <module>
    parse_and_run()
  File "/hpc/group/cosmology/lna18/rsim_photometry/mk_lc.py", line 553, in parse_and_run
    run(args.oid, args.band, inputdir=args.inputdir, outputdir=args.outputdir)
  File "/hpc/group/cosmology/lna18/rsim_photometry/mk_lc.py", line 484, in run
    lc_filename = make_lc(oid, band, exptime, coord, area_eff, in_tab, t_pointing,t_sca, inputdir=inputdir, outputdir=outputdir)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/rsim_photometry/mk_lc.py", line 347, in make_lc
    sn_phot = calc_sn_photometry(sub_img, sub_wcs, psf, coord)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/rsim_photometry/mk_lc.py", line 217, in calc_sn_photometry
    sn_phot = psf_phot(img.data, psf, init_sn, wcs=wcs, forced_phot=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/group/cosmology/lna18/phrosty/phrosty/photometry.py", line 166, in psf_phot
    psf_results = psfphot(scienceimage, init_params=init_params)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/lna18/.local/lib/python3.11/site-packages/photutils/psf/photometry.py", line 933, in __call__
    fit_models = self._fit_sources(data, init_params, error=error,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/lna18/.local/lib/python3.11/site-packages/photutils/psf/photometry.py", line 625, in _fit_sources
    yi, xi, cutout = self._define_fit_data(sources_, data, mask)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hpc/home/lna18/.local/lib/python3.11/site-packages/photutils/psf/photometry.py", line 481, in _define_fit_data
    raise ValueError(msg)
ValueError: Source at (1036, 978) is completely masked. Remove the source from init_params or correct the input mask.
```

**Comment by laldoroty** [comment]
Never mind. Figured it out. This is what happens when there are NaNs where the source should be.

**Comment by wmwv** [comment]
Yeah, I think that's fine and it's just a thing that's going to happen.
