### ISSUE TITLE
Not all bands worked in most recent run

### ISSUE THREAD

**Issue by laldoroty** [Roman-Supernova-PIT/diff-img#26]
F, J, and Z all failed in the 5-template run very early on. Didn't even get through the first image. Full output is:

```
taskID 1
band F184
The template images are:
filter pointing sca
------ -------- ---
  F184      276  10
  F184      281  17
  F184      661  15
  F184     1432  13
  F184     2203  10
*************************************************************
F184 34973 6 - F184 276 10

MeLOn CheckPoint [Roman_TDS_simple_model_F184_34973_6.fits]: Run Python Wrapper of SExtractor!
MeLOn CheckPoint [Roman_TDS_simple_model_F184_34973_6.fits]: SExtractor found [5080] sources!
MeLOn CheckPoint [Roman_TDS_simple_model_F184_34973_6.fits]: PYSEx output catalog contains [5080] sources!

MeLOn CheckPoint [Roman_TDS_simple_model_F184_276_10.fits]: Run Python Wrapper of SExtractor!
MeLOn CheckPoint [Roman_TDS_simple_model_F184_276_10.fits]: SExtractor found [4814] sources!
MeLOn CheckPoint [Roman_TDS_simple_model_F184_276_10.fits]: PYSEx output catalog contains [4814] sources!
MeLOn CheckPoint: Run SWarp Command ... 
 cd /tmp/PYSWarp_lgrm1dtc && swarp /work/lna18/imsub_out/skysub/skysub_Roman_TDS_simple_model_F184_276_10.fits -IMAGEOUT_NAME /tmp/PYSWarp_lgrm1dtc/skysub_Roman_TDS_simple_model_F184_276_10.tmp_resamp.fits -WEIGHTOUT_NAME /tmp/PYSWarp_lgrm1dtc/skysub_Roman_TDS_simple_model_F184_276_10.tmp_resamp_weight.fits -c /tmp/PYSWarp_lgrm1dtc/PYSWarp_rdcbxyajswarp_config/PYSWarp.swarp
----- SWarp 2.38.0 started on 2024-08-05 at 10:43:24 with 78 threads

> Creating NEW output image ...
> WARNING: FITS header data read in /tmp/PYSWarp_lgrm1dtc/skysub_Roman_TDS_simple_model_F184_276_10.tmp_resamp.head

------- Output File skysub_Roman_TDS_simple_model_F184_276_10.tmp_resamp.fits:
    "no ident"  WEIGHTED  EXT. HEADER  4088x4088  32 bits (floats)
    Center: 00:30:28.24 -44:44:47.8   7.19'x7.19'  Scale: 0.1056 ''/pixel
    Gain: 0 e-/ADU   Flux scaling (astrom/photom): 1 X / 1 X

-------------- File skysub_Roman_TDS_simple_model_F184_276_10.fits:
    "no ident"  unweighted  no ext. header  4088x4088  64 bits (floats)
    Center: 00:30:09.80 -44:50:17.0   7.42'x7.42'  Scale: 0.1089 ''/pixel
    Gain: 1 e-/ADU   Flux scaling (astrom/photom): 0.9392 X / 1 X
    Background: 0.1117303   RMS: 21.74594

-------------- Co-adding frames            
Maximum overlap density: 1 frame
> All done (in 2.0 s)
/work/lna18/imsub_out/align/align_skysub_Roman_TDS_simple_model_F184_276_10_-_F184_34973_6.fits does not sufficiently overlap with the SN. 
/work/lna18/imsub_out/skysub/skysub_Roman_TDS_simple_model_F184_34973_6.fits does not sufficiently overlap with the SN. 
Images F184 34973 6 and F184 276 10 do not sufficiently overlap to do image subtraction.
Traceback (most recent call last):
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 328, in <module>
    parse_and_run()
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 324, in parse_and_run
    run(args.oid, args.band, args.n_templates, args.verbose)
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 252, in run
    animate(dd_stamps,pointings,oid,band,f'{oid}/{oid}_{band}_{t_pointing}_{t_sca}_SFFT.gif')
  File "/hpc/group/cosmology/lna18/rsim_photometry/sfft_and_animate.py", line 208, in animate
    animate_stamps(frames,savepath,metadata,labels,staticlabel=band)
  File "/hpc/group/cosmology/lna18/phrosty/phrosty/plotting.py", line 209, in animate_stamps
    im = ax.imshow(stamps[0], animated=True)
                   ~~~~~~^^^
IndexError: list index out of range
```

So, looks like they failed on the animation part. Weirdly, it looks like the line where I call 'animate()' is indented too far inside a loop. Not really sure how this didn't catch the other bands.

**Comment by laldoroty** [comment]
Resolved incidentally in https://github.com/Roman-Supernova-PIT/diff-img/issues/24. Closing.
